* Nothing to Hide
** Warning
This project is on a very early stage of development. On same rare
occasions it might tele-transport your computer to event
horizon. Also, this version only supports the English language, sorry :(
** The Problem
Email is [[https://en.wikipedia.org/wiki/Email_security#Privacy_concerns][not a very private method of communication.]]
** Current Solutions
There has been several attempts to make email securing such as using end-to-end
encryption. Technologies such as [[https://en.wikipedia.org/wiki/GNU_Privacy_Guard][GPG]] do provide great security. But
this and other methods of encryption have failed to gather
traction. Without being popular the system is not very effective since
it requires all parties involved in communication to have a special
setup and to have create a public/private key pair. Also, many of the
current solutions are hard to setup and configure for many
users. Nothing to Hide tries a radically different approach to
securing email.
** Our Solution
Nothing to Hide attempts to make email more secure by making messages
more vague, in such a way that the intended recipient can still
understand the message but snoopers can't. In it's current form it
only available as [[https://www.google.com/intl/en/chrome/browser/][Google Chrome]] and [[http://www.chromium.org/Home][Chromium]] add-on for [[https://mail.google.com][Gmail]]. A
[[https://www.mozilla.org/en-US/firefox/new/][Firefox]] version of the add-on is on the works.
** Installation
First install our [[https://chrome.google.com/webstore/detail/keiegjchmoggjbpgfjdjghbiicpjneoe/publish-accepted][Chrome extension]]. Also, you need the following installed:
- [[http://openjdk.java.net/][Java]] (Only tested with Java 7 and higher)
- [[http://python.org/][Python]] (Only tested with Python 2.7.x and higher)
- [[https://pypi.python.org/pypi/pip/][pip]] (Only tested with 1.4.x and higher) How to install pip on
  [[http://stackoverflow.com/questions/4750806/how-to-install-pip-on-windows][Windows]] and [[http://docs.python-guide.org/en/latest/starting/install/osx/][Mac OS X.]] Ubuntu users run =sudo apt-get install python-pip=.
*** Automated
The automated method has only been tested in GNU/Linux and Mac OS
X. It should work for other Unix operating systems. Windows users have
to use the manual method.
**** Via Curl
If you're using =curl= type the following command:
=curl -L https://raw.github.com/climatewarrior/nothing-to-hide/master/utils/installer.sh | sh=
**** Via Wget
If you're using =wget= type:
=wget --no-check-certificate https://raw.github.com/climatewarrior/nothing-to-hide/master/utils/installer.sh -O - | sh=
*** Manual
**** Windows
**** *nix
** How to use
- Start the server with:
=sh utils/run.sh=
- Open Chrome or Chromium and open your Gmail account.
- Write your email messages as you normally would.
- Before sending them hit the Nothing to Hide black icon on the add-on
  icon area.
- Revise your messages and send them.
- Shutdown the server whenever you wish or just leave it running in
  the background.
* Developer
** Contributing
*** Building
**** Dependencies
- [[https://github.com/dat/pyner][Pyner]]
- [[http://flask.pocoo.org/][Flask]]
- [[https://github.com/dat/stanford-ner][Stanford NER]]
- [[http://nlp.stanford.edu/software/tagger.shtml][Stanford Tagger]]
- [[https://pypi.python.org/pypi/nltk/2.0.1][NLTK]]
